name: test

on:
  workflow_dispatch:
  pull_request: {branches: ["main"]}

jobs:
  build:
    name: Build and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['16.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Install pnpm v8
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install deps and build (with cache)
        run: pnpm install

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm build

